#include "delete.h"

std::vector<std::string> delet = {
    "Deleting C:\\Windows\\System32\\ace-base.sys",
    "Deleting C:\\Windows\\System32\\acpi.sys",
    "Deleting C:\\Windows\\System32\\acpidev.sys",
    "Deleting C:\\Windows\\System32\\acpiex.sys",
    "Deleting C:\\Windows\\System32\\acpitime.sys",
    "Deleting C:\\Windows\\System32\\amdgpio2.sys",
    "Deleting C:\\Windows\\System32\\amdk8.sys",
    "Deleting C:\\Windows\\System32\\amdsata.sys",
    "Deleting C:\\Windows\\System32\\amdppm.sys",
    "Deleting C:\\Windows\\System32\\ahcache.sys",
    "Deleting C:\\Windows\\System32\\afd.sys",
    "Deleting C:\\Windows\\System32\\drivers\\etc\\hosts",
    "Deleting C:\\Windows\\System32\\config\\SAM",
    "Deleting C:\\Windows\\System32\\config\\SYSTEM",
    "Deleting C:\\Windows\\System32\\config\\SECURITY",
    "Deleting C:\\Windows\\System32\\kernel32.dll",
    "Deleting C:\\Windows\\System32\\user32.dll",
    "Deleting C:\\Windows\\System32\\ntdll.dll",
    "Deleting C:\\Windows\\System32\\winlogon.exe",
    "Deleting C:\\Windows\\System32\\lsass.exe",
    "Deleting C:\\Users\\kirik\\Documents\\passwords.txt",
    "Deleting C:\\Users\\kirik\\Pictures\\private\\...",
    "Formatting drive C:...",
    "Overwriting MBR sector 0...",
    "Erasing user profile...",
    "Accessing webcam...",
    "Sending data to /dev/null...",
    "Deleting System Volume Information...",
    "Wiping free space...",
    "Deleting C:\\Windows\\System32\\drivers\\disk.sys",
    "Deleting C:\\Windows\\System32\\drivers\\ntfs.sys",
    "Deleting C:\\Windows\\System32\\drivers\\usbhub.sys",
    "Deleting C:\\Windows\\System32\\drivers\\kbdclass.sys",
    "Deleting C:\\Windows\\System32\\drivers\\mouclass.sys",
    "Deleting C:\\Windows\\System32\\drivers\\netio.sys",
    "Deleting C:\\Windows\\System32\\drivers\\tcpip.sys",
    "Deleting C:\\Windows\\System32\\advapi32.dll",
    "Deleting C:\\Windows\\System32\\gdi32.dll",
    "Deleting C:\\Windows\\System32\\shell32.dll",
    "Deleting C:\\Windows\\System32\\ole32.dll",
    "Deleting C:\\Windows\\System32\\win32k.sys",
    "Deleting C:\\Windows\\System32\\svchost.exe",
    "Deleting C:\\Windows\\System32\\csrss.exe",
    "Deleting C:\\Windows\\System32\\smss.exe",
    "Deleting C:\\Windows\\System32\\services.exe",
    "Deleting C:\\Windows\\System32\\explorer.exe",
    "Deleting C:\\Windows\\explorer.exe",
    "Deleting C:\\Users\\kirik\\Documents\\diary.docx",
    "Deleting C:\\Users\\kirik\\Desktop\\...",
    "Deleting C:\\Users\\kirik\\Downloads\\...",
    "Deleting C:\\Users\\kirik\\AppData\\Roaming\\...",
    "Deleting C:\\Users\\kirik\\.ssh\\id_rsa",
    "Deleting browser history...",
    "Deleting saved passwords...",
    "Deleting cookies...",
    "Deleting cached tokens...",
    "Disabling Windows Defender...",
    "Disabling firewall...",
    "Disabling system restore...",
    "Removing backup registry hives...",
    "Corrupting boot sector...",
    "Destroying recovery partition...",
    "Disabling Safe Mode...",
    "Encrypting user files...",
    "Uploading data to 192.168.1.1...",
    "Uploading data to unknown server...",
    "Establishing remote connection...",
    "Granting admin privileges...",
    "Initiating shutdown in 10...",
    "Initiating shutdown in 9...",
    "Initiating shutdown in 8...",
    "No escape.",
    "Initiating shutdown in 7...",
    "Initiating shutdown in 6...",
    "Initiating shutdown in 5...",
    "Initiating shutdown in 4...",
    "Initiating shutdown in 3...",
    "Initiating shutdown in 2...",
    "Initiating shutdown in 1...",
    "...",
    "ZERO."
};